### ISSUE TITLE
Reduce size of coins

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-crypto#193]
The coins should be 40px X 40px

![image](https://user-images.githubusercontent.com/1935403/112177907-9086e380-8bb6-11eb-83b1-db3553bbca8d.png)

**Comment by jabinx92** [comment]
can i work on this issue?

**Comment by nilisha-jais** [comment]
I'll do it

**Comment by swarajpure** [comment]
> can i work on this issue?

@jabinx92 This issue was assigned to @nilisha-jais as per discussion on our discord server.

We (Real Dev Squad) are a community of developers consisting on college students and working professionals. We communicate over Discord. You might want to join the community, you'll get A LOT to learn 😄
We have got projects like this repository which use simple HTML, CSS and vanilla JavaScript and also projects based on React, Ember and Vue for frontend and on Node for backend. Since we're open source, you can show your work which you do here to the interviewers as well 🎉 
No matter what your expertise level is, we've always got something for everyone! ⚡ 

Invitation link: https://discord.gg/8n4hMSDG
